name: Run tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Install a version of Chrome that's supported by mocha-chromedriver"
        run: |
          VERSION_STRING="111.0.5563.146-1"
          wget "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${VERSION_STRING}_amd64.deb"
          sudo dpkg -i "google-chrome-stable_${VERSION_STRING}_amd64.deb"

      - run: npm install

      - run: npm test
        env:
          MOCHA_WEBDRIVER_LOGDIR: testoutput
          SELENIUM_BROWSER: chrome
